name: Check Good writing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install write-good
      # TODO: include at some point
      #- run: npx write-good *.md